[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
raydium_cpi = "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK"

[programs.mainnet]
raydium_cpi = "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK"

[programs.devnet]
raydium_cpi = "devi51mZmdwUJGU9hjN27vEz64Gps7uUefqxg27EAtH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/campv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
